namespace :simulate do 
  task :manage do
    require_relative 'lib/managed_simulator/wander'
    include ManagedSimulator
    
    run
  end

  task :unmanage do
    require_relative 'lib/unmanaged_simulator/wander'
    UnmanagedSimulator.run
  end
end
