# frozen_string_literal: true

require_relative 'lib/particle_passage_simulation/experiment'
require_relative 'lib/tools/console_manager'

task :run do
  collected_data = collect_data

  Tools::ConsoleManager.output <<-OUTPUT
    ============== DATA ==============
    Quantity: \t\t\t\t#{quantity}

    Characteristics of radiation and the layer of substance:
    \t substance thickness:      #{collect_data.dig(:meta, :h)}
    \t coocrdinate:              #{collect_data.dig(:meta, :x_0)}
    \t radiation angle in grade: #{collect_data.dig(:meta, :teta_0)}

    Characteristics of the process of interaction of particles with substance:
    \t mean free run length:            #{collect_data.dig(:character, :l)}
    \t particle absorption probability: #{collect_data.dig(:character, :p_a)}
    \t scattering indicator:            #{collect_data.dig(:character, :n)}
    \t average scattering angle:        #{collect_data.dig(:character, :omega_av)}
    ==============/DATA ==============
  OUTPUT

  puts 'Running...'
  experiment = ParticlePassageSimulation::Experiment.call(collected_data)

  puts 'Process...'
  statistic = experiment.statistic
end

def collect_data
  # {
  #   quantity -- розмір вибірки для статичної оцінки результатів
  #   meta{
  #     h        -- товщина шару
  #     x_0      -- координата поверхні шару що опромінюється
  #     teta_0   -- кут падіння випромінювання на поверхню шару
  #   }
  #   character {
  #     l        -- середня довжина вільного пробігу частинок у речовені шару
  #     p_a      -- ймовірність поглинання частинок при взаємодії з речовеною
  #     n        -- модельний параметер індикатриси розсіювання
  #     omega_av -- середніц кут розсіювання частинок при взаємодії з речовиною
  #   }
  # }
  {
    quantity:  collect_quantitny,
    meta:      collect_meta,
    character: collect_character
  }
end

def collect_quantitny
  Tools::ConsoleManager.input_i("Set sample size <default: 10_000> = ") || 10_000
end

def collect_meta
  Tools::ConsoleManager.output "Set characteristics of radiation and the layer of substance:"
  {
    h:      Tools::ConsoleManager.input_f("\t substance thickness        <default: 2> = ") || 2.0,
    x_0:    Tools::ConsoleManager.input_f("\t coocrdinate                <default: 0> = ") || 0.0,
    teta_0: Tools::ConsoleManager.input_f("\t cos of radiation angle     <default: 1> = ") || 1.0
  }
end

def collect_character
  Tools::ConsoleManager.output "Set characteristics of the process of interaction of particles with substance:"
  {
    l:       Tools::ConsoleManager.input_f("\t mean free run length              <default: 1>     = ") || 1.0, # аналогічно 74
    p_a:      Tools::ConsoleManager.input_f("\t particle absorption probability   <default: 0.001> = ") || 0.001,
    n:        Tools::ConsoleManager.input_f("\t scattering indicator              <default: 1>     = ") || 0.1
    omega_av: Tools::ConsoleManager.input_f("\t cos ofaverage scattering angle    <default: 0>     = ") || 0.0 # проблеми з розумінням Ж мабуть потрібно відносно середнього значення рандомізувати відхилення
  }
end
